#!/bin/bash -eu

filter=('cat')

while getopts ":p:" opt
do
    case "$opt" in
        p)
            filter=('grep' '-E' "$OPTARG")
        ;;
        \?)
            echo >&2 "$0: invalid option: -$OPTARG"
            echo >&2
            echo >&2 "Usage: $0 [-p <pattern>]"
            echo >&2
            echo >&2 "Flags:"
            echo >&2 "  -p <pattern> Only return files matching the specified regex."
            exit 1
            ;;
    esac
done

comm -13 \
     <(bazel query 'kind("source file", deps(//...))' | cut -c3- | tr ':' '/' | "${filter[@]}" | sort) \
     <(git ls-files | "${filter[@]}" | sort)
