java_library(
    name = "config",
    srcs = glob(["*.java"]),
    visibility = ["//sync-repos:__subpackages__"],
    deps = [
        "//3rdparty/jvm/com/fasterxml/jackson/core:jackson-annotations",
        "//3rdparty/jvm/com/fasterxml/jackson/core:jackson-core",
        "//3rdparty/jvm/com/fasterxml/jackson/core:jackson-databind",
        "//3rdparty/jvm/com/fasterxml/jackson/dataformat:jackson-dataformat-yaml",
        "//3rdparty/jvm/com/fasterxml/jackson/datatype:jackson-datatype-guava",
        "//3rdparty/jvm/com/google/auto/value:auto-value",
        "//3rdparty/jvm/com/google/guava",
        "//3rdparty/tools:auto-value",
    ],
)
