java_library(
    name = "cli",
    srcs = ["Options.java"],
    visibility = ["//sync-repos:__subpackages__"],
    deps = [
        "//3rdparty/jvm/com/google/auto/value:auto-value",
        "//3rdparty/jvm/net/sf/jopt-simple",
        "//3rdparty/tools:auto-value",
    ],
)
