workspace(name = "spotify_bazel_tools")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "53059e0cda4517afe5a3907f77d1a379577773f2b1659fed8dc668b3f110a7d3",
    strip_prefix = "rules_go-0dc1f9e0741d766780e931d49790ddb501bb34c9",  # branch master
    urls = ["https://github.com/bazelbuild/rules_go/archive/0dc1f9e0741d766780e931d49790ddb501bb34c9.zip"],
)

http_archive(
    name = "io_bazel",
    sha256 = "8c33ee6b198359265186f95fbd6aa7ad4e84c3a1fd9b14d22efc3ffb22699f63",
    strip_prefix = "bazel-0.7.0",  # Should match current Bazel version
    urls = [
        "http://bazel-mirror.storage.googleapis.com/github.com/bazelbuild/bazel/archive/0.7.0.tar.gz",
        "https://github.com/bazelbuild/bazel/archive/0.7.0.tar.gz",
    ],
)

http_archive(
    name = "com_github_bazelbuild_buildtools",
    sha256 = "5772dfbd67f6fc7ad8aa07fb5896858d4c65b8aee7a54ada69271b962d69535f",
    strip_prefix = "buildtools-b0f22bba2532e4f62eb815a86637e7ac5372e142",  # branch superhack
    urls = ["https://github.com/dflemstr/buildtools/archive/b0f22bba2532e4f62eb815a86637e7ac5372e142.zip"],
)

##
## Add Go support
##
load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")

go_rules_dependencies()

go_register_toolchains()

##
## Load all Maven dependencies, generated by sync-deps/run
##
load("//3rdparty:workspace.bzl", "maven_dependencies")
load("//3rdparty:load.bzl", "declare_maven")

maven_dependencies(declare_maven)

##
## Alias some external tools that are used by tools/ to do their thing
##

bind(
    name = "tool/buildifier",
    actual = "@com_github_bazelbuild_buildtools//buildifier",
)

bind(
    name = "tool/buildozer",
    actual = "@com_github_bazelbuild_buildtools//buildozer",
)

bind(
    name = "tool/unused-deps",
    actual = "@com_github_bazelbuild_buildtools//unused_deps",
)
