java_library(
    name = "cliutils",
    srcs = glob(["*.java"]),
    visibility = ["//cli-utils:__subpackages__"],
    deps = [
        "//3rdparty/jvm/ch/qos/logback:logback-classic",
        "//3rdparty/jvm/ch/qos/logback:logback-core",
        "//3rdparty/jvm/com/github/tomas-langer:chalk",
        "//3rdparty/jvm/com/google/auto/value:auto-value",
        "//3rdparty/jvm/org/slf4j:slf4j-api",
        "//3rdparty/tools:auto-value",
    ],
)
