java_library(
    name = "util",
    srcs = glob(["*.java"]),
    visibility = ["//sync-deps:__subpackages__"],
    deps = [
        "//3rdparty/jvm/com/google/guava",
        "//3rdparty/jvm/org/slf4j:slf4j-api",
    ],
)
