java_library(
    name = "format",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//3rdparty/jvm/com/google/auto/value:auto-value",
        "//3rdparty/jvm/com/google/googlejavaformat:google-java-format",
        "//3rdparty/jvm/com/google/guava",
        "//3rdparty/jvm/net/sf/jopt-simple",
        "//3rdparty/tools:auto-value",
        "//format/src/main/scala/com/spotify/format",
    ],
)
