java_test(
    name = "PathUtilsTest",
    size = "small",
    srcs = ["PathUtilsTest.java"],
    deps = [
        "//3rdparty/jvm/com/google/guava",
        "//3rdparty/jvm/com/google/jimfs",
        "//3rdparty/jvm/com/squareup/okio",
        "//3rdparty/jvm/org/hamcrest:java-hamcrest",
        "//sync-deps/src/main/java/com/spotify/syncdeps/util",
    ],
)
